### ISSUE TITLE
google.protobuf.message.DecodeError: Tag had invalid wire type.

### ISSUE THREAD

**Issue by MichaelQWang** [ahangchen/ncs_detection#1]
## Hi ahangchen,
When i test my graph with my jpg file,it's output "google.protobuf.message.DecodeError: Tag had invalid wire type."
maybe my train step has mistake.how to tackle the problem or which step am i wrong?
Thanks in advance.

I use labelimg to dealwith jpg file.
ImageSets file like this:
########################
markimg39.jpg markimg39.xml
markimg50.jpg markimg50.xml
markimg67.jpg markimg67.xml
timg (18).jpg timg (18).xml
timg (33).jpg timg (33).xml
timg (19).jpg timg (19).xml
#######################

## **_what's the "0.487500	0.320675	0.670000	0.433193" mean?_**
假设你的打的标签是这样一个文件raw_label.txt，假装我们数据集只有两张图片：
data/strange_animal/1017.jpg 0.487500	0.320675	0.670000	0.433193
data/strange_animal/1018.jpg 0.215000	0.293952	0.617500	0.481013

labelmap_coco.prototxt like this:
######################################
item {
  name: "none_of_the_above"
  label: 0
  display_name: "background"
}
item {
  name: "markpoint"
  label: 1
  display_name: "markpoint"
}

# **labelmap_coco.pbtxt like this: what's the name: "/m/01g317" mean?can i write this as same as display_name?**
###########################
item {
  name: "markpoint"
  label: 1
  display_name: "markpoint"
}
##############################
item {
  name: "/m/01g317"
  id: 1
  display_name: "new"
}
item {
  name: "/m/0199g"
  id: 2
  display_name: "bicycle"
}
#########################

# **_my xml like this:_**
###########################
`<annotation>
	<folder>train</folder>
	<filename>markimg2.jpg</filename>
	<path>H:\Tensorflow_ObjectDetection_MarkLabel\src\research\customized_model\images\pre\train\markimg2.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>640</width>
		<height>480</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>markpoint</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>133</xmin>
			<ymin>225</ymin>
			<xmax>212</xmax>
			<ymax>298</ymax>
		</bndbox>
	</object>
	<object>
		<name>markpoint</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>265</xmin>
			<ymin>133</ymin>
			<xmax>338</xmax>
			<ymax>194</ymax>
		</bndbox>
	</object>
	<object>
		<name>markpoint</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>388</xmin>
			<ymin>133</ymin>
			<xmax>465</xmax>
			<ymax>196</ymax>
		</bndbox>
	</object>
	<object>
		<name>markpoint</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>381</xmin>
			<ymin>238</ymin>
			<xmax>472</xmax>
			<ymax>326</ymax>
		</bndbox>
	</object>
	<object>
		<name>markpoint</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>252</xmin>
			<ymin>357</ymin>
			<xmax>344</xmax>
			<ymax>462</ymax>
		</bndbox>
	</object>
</annotation>`
##############################
pi@raspberrypi:~/workspace/ncs_detection $ python ncs_detection_testmarkpoint.py
mkdir: cannot create directory ‘r10_tmp’: File exists
rm: cannot remove 'r10_tmp/*': No such file or directory
[INFO] finding NCS devices...
[INFO] found 1 devices. device0 will be used. opening device0...
[INFO] loading the graph file into RPi memory...
[INFO] allocating the graph on the NCS...
<mvnc.mvncapi.Graph instance at 0x6cbce260>
('data/labelmap_coco.pbtxt', 1)
Traceback (most recent call last):
  File "ncs_detection_testmarkpoint.py", line 172, in <module>
    count_for_video_ncs(img_dir, start_index, end_index)
  File "ncs_detection_testmarkpoint.py", line 129, in count_for_video_ncs
    category_index = label_prepare(PATH_TO_LABELS, NUM_CLASSES)
  File "ncs_detection_testmarkpoint.py", line 96, in label_prepare
    label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
  File "/home/pi/workspace/ncs_detection/object_detection/utils/label_map_util.py", line 122, in load_labelmap
    label_map.ParseFromString(label_map_string)
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.5.1-py2.7.egg/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.5.1-py2.7.egg/google/protobuf/internal/python_message.py", line 1083, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.5.1-py2.7.egg/google/protobuf/internal/python_message.py", line 1109, in InternalParse
    new_pos = local_SkipField(buffer, new_pos, end, tag_bytes)
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.5.1-py2.7.egg/google/protobuf/internal/decoder.py", line 850, in SkipField
    return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.5.1-py2.7.egg/google/protobuf/internal/decoder.py", line 820, in _RaiseInvalidWireType
    raise _DecodeError('Tag had invalid wire type.')
google.protobuf.message.DecodeError: Tag had invalid wire type.
pi@raspberrypi:~/workspace/ncs_detection $

**Comment by ahangchen** [comment]
I label the imgs with four floats to represent xmin, ymin, xmax, ymax for each bounding box in a file.
The step you mentioned above is about how to convert this file to xml in coco style.
Unless your xml generated by labelImg has already been coco style, you have to convert your label data to coco style and convert them to lmdb for caffe training.

**Comment by MichaelQWang** [comment]
After I trained the model again and check the every step code.I have tackled the problem.I write the id with label for mistake.below is right.
Thanks very much.
###########
item {
  name: "markpoint"
  id: 1
  display_name: "markpoint"
}
